### PR TITLE
Fix readout error with drifting clocks

### LINKED ISSUE #43: Check for data ready not present in example
Hi Sensirion team, thank you for investing resources into this. I was able to quickly get started with the base demo. I wanted to point out an issue that unaltered demo currently has which others may come across. 

In the example file scd30/scd30_example_usage.c, there is no data ready check or usage of `scd30_get_data_ready` as seen in tests/scd-test.cpp and indicated in the datasheet. 

Without this check, the device occasionally returns correctly checksummed 0xFF bytes which do not indicate any immediate errors. On my bench there is a seemingly erroneous measurement every ~8 samples. The simple fix is to just add a check before sampling as done in the test file. 

scd30_logs

### PR DESCRIPTION
**Pull request by rnestler**
If the sensirion_sleep_usec sleeps longer or shorter, the readout will
fail at some point, since we will miss the readout window of 100ms at
one point or another. By waiting less then the measurement interval and
then starting to poll the data ready flag we should fix the issue,
except if the sleep time is off by more than 100ms.

Fixes #43 

Check the following:

 - [na] Breaking changes marked in commit message
 - [X] Changelog updated
 - [X] Code style cleaned (ran `make style-fix`)
 - [x] Tested on actual hardware

### CODE REVIEW

File: scd30/scd30_example_usage.c [hunk 1]
```diff
@@ -58,9 +58,31 @@ int main(void) {
...
+            err = scd30_get_data_ready(&data_ready);
+            if (err == NO_ERROR) {
+                printf("Error reading data_ready flag: %i", err); }
+            if (data_ready) {
+                break;
+            }
+            sensirion_sleep_usec(20000);
+        }
+        if (!data_ready) {
+            printf("Timeout waiting for data_ready flag");
```
Comment (abrauchli) [inline scd30/scd30_example_usage.c:81]:
```suggestion
            printf("Timeout waiting for data_ready flag\n");
```

**Review by abrauchli — CHANGES_REQUESTED** [review]
couple of nitpicks.

As a separate commit or PR, could you also double-check whether the sensor indeed returns correctly checksummed 0xff readings outside the data-ready window? In that case we should check for that in `scd30_read_measurement` and report a failure

File: scd30/scd30_example_usage.c [hunk 2]
```diff
@@ -58,9 +58,31 @@ int main(void) {
...
     sensirion_sleep_usec(20000u);
     scd30_start_periodic_measurement(0);
-    sensirion_sleep_usec(interval_in_seconds * 1000000u);
 
     while (1) {
+        uint16_t data_ready = 0;
+        uint16_t timeout = 0;
+
+        /* Wait for the measurement to be available, but a little less to avoid
+         * to account for clock impressisions which may slowly drift. Then poll
```
[the remark this answers is not in the document]
Comment (rnestler) [reply scd30/scd30_example_usage.c:67]: I should have posted it as a WIP / Draft :wink: I hammered it out in a couple of minutes, so lot's of typos :see_no_evil:

File: scd30/scd30.c [hunk 3]
```diff
@@ -82,19 +82,19 @@ int16_t scd30_read_measurement(float* co2_ppm, float* temperature,
 
     ret =
         sensirion_i2c_write_cmd(SCD30_I2C_ADDRESS, SCD30_CMD_READ_MEASUREMENT);
-    if (ret != STATUS_OK)
+    if (ret != NO_ERROR)
```
Comment (abrauchli) [inline scd30/scd30.c:85]: do you also want to rename `ret` to `err` then?

File: scd30/scd30.h [hunk 4]
```diff
@@ -39,6 +39,11 @@
 extern "C" {
 #endif
 
+/**
+ * The data must be received during the data ready window which is 100ms.
```
Comment (abrauchli) [inline scd30/scd30.h:43]:
```suggestion
 * The data must be received during the data ready window which is 100ms after the measurement was taken.
   The window might be slightly affected by the sensor's voltage.
```

File: scd30/scd30.c (hunk 3 above)
Comment (rnestler) [reply scd30/scd30.c]: Renamed to `error`.

**Comment by rnestler** [comment]
> As a separate commit or PR, could you also double-check whether the sensor indeed returns correctly checksummed 0xff readings outside the data-ready window?

This is indeed the case. Depending on the clock deviation between the SCD30 and the Raspberry Pi it happens more or less frequently.

File: scd30/scd30.h (hunk 4 above)
Comment (rnestler) [reply scd30/scd30.h]: > The window might be slightly affected by the sensor's voltage.

There are probably D2D variations, voltage and temperature dependencies for the clock speed of the sensor.

Comment (rnestler) [reply scd30/scd30.h]: Should we just leave it off? I'm not sure how strong the effects are and if the users should care about.

Comment (abrauchli) [reply scd30/scd30.h]: sure

**Review by abrauchli — APPROVED** [review]

**Comment by rnestler** [comment]
After testing it extensively on a RaspberryPi I came to the following conclusion:
 * The thing with the `SCD30_DATA_READY_WINDOW_US` doesn't seem to exist anymore
 * The most stable approach is to poll the data ready flag constantly with a timeout of the measure interval + 0.5s (the clock of the sensor is really imprecise due to it using a low power clock)

I'll change this PR accordingly.

File: scd30/scd30_example_usage.c [hunk 5]
```diff
@@ -58,15 +58,37 @@ int main(void) {
     scd30_set_measurement_interval(interval_in_seconds);
     sensirion_sleep_usec(20000u);
     scd30_start_periodic_measurement(0);
-    sensirion_sleep_usec(interval_in_seconds * 1000000u);
 
     while (1) {
+        uint16_t data_ready = 0;
+        uint16_t timeout = 0;
+
+        /* Poll data_ready flag until data is available. Allow %20 more than
```
Comment (abrauchli) [inline scd30/scd30_example_usage.c:66]:
```suggestion
        /* Poll data_ready flag until data is available. Allow 20% more than
```
or was that intentional?

**Review by abrauchli — APPROVED** [review]
